name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.0
  firebase_authentication: ^0.0.6
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mayo_cloud_firestore:
    git:
      url: https://github.com/Flutter-libraries/mayo_cloud_firestore
      ref: v1.0.9
  mayo_cloud_storage:
    git:
      url: https://github.com/Flutter-libraries/mayo_cloud_storage
      ref: v0.0.6
  mayo_components:
    git: 
      url: https://github.com/Flutter-libraries/mayo_components
      ref: v0.0.5

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  fake_cloud_firestore: ^1.3.2
  firebase_auth_mocks: ^0.8.7
  firebase_storage_mocks: ^0.5.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

scripts:
  build: "flutter pub run build_runner build --delete-conflicting-outputs"